env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "cxfM+Pyjsxy+Es9bu/+Bg1r/TMSE1NhscwqGILTPAMrgj55iRhV3qzfZIsnkzGzPqv/Mtk0r0LOPpdl65T7KTN15rMJ0WHArx3yBvbJE3OmYXHuL3vA1+V4QiesR4nrW9nb8G/ZAKHRwxI72BxXLQONIDUbzYhzfictpDpqNCS9ZVttbPHLQBHNSNNswduGGTxTbcbHdMFByM0i5P4u6nC0Of0SXD53TFoYZ/SxDwZnpujWHu8LNLtPA/fJ0+A6svaB9lh007l1TdJi/zjcruscMK5D1rniUxGCr2iX+EIRI/qIZC3jA5UICX6k2nuGP8Vz09hqaekxi9X1nef9AVtIwjDfjDIcg6aGcBfxOx14xtAu6eFvRY4XupohuMNUlNy81aUNaei9qffq7e3dyw32SQH0dgN9wKnTLatV+5yJuBUcNmNTcZGV5XCxC8xY4OCp/PMhG0p91H4CxyZ7ptMoZ0OqqUdo4pUZLyBKAKrYbDvTc6/vpvswb4yLkhQAnbfBHL3nTYjyOuFXVE76PkIiNt+Sf15XcDNbC7lSOHDqWZ2+g8z1HuuygkdDU3Te1PX/DaXj1GjiUogjYQZpuYR23VOfn9YN3AG/71nPsoG45T39rF8D8XNPHzNh6exlYijCnpFaeempiaHdanoSTbDYo+qQHm0bpA10wOs7/nWY="



language: cpp
compiler:
  - gcc

# This is a lie: we don't need sudo but this is required to get an
# Ubuntu image with a libc that isn't ancient, and with cmocka libs.
sudo: required
dist: trusty

language: c
compiler:
  - gcc
  - clang

addons:
  coverity_scan:
    project:
      name: "01org/tpm2.0-tools"
      description: "Build submitted via Travis CI"
    notification_email: william.c.roberts@intel.com
    build_command_prepend: "./bootstrap && ./configure && make clean"
    build_command:   "make -j4"
    branch_pattern: coverity_scan
  apt:
    packages:
    - autoconf-archive
    - openssl
    - libssl-dev
    - libcurl4-openssl-dev
    - libdbus-1-dev
    - libglib2.0-dev
    - pkg-config 
    - libcmocka0
    - libcmocka-dev

  coverity_scan:
    project:
      name: "PeterHuewe/tpm2.0-tools"
      description: "Build submitted via Travis CI"
    notification_email: peterhuewe@gmx.de
    build_command_prepend: "./bootstrap; ./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: scan_coverity

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install: 
    - wget https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm532.tar
    - sha256sum ibmtpm532.tar | grep -q abc0b420257917ccb42a9750588565d5e84a2b4e99a6f9f46c3dad1f9912864f
    - mkdir ibmtpm532 && pushd ibmtpm532 && tar xzf ../ibmtpm532.tar && pushd ./src && make
    - ./tpm_server &
    - popd && popd
    - git clone https://github.com/01org/TPM2.0-TSS.git
    - pushd TPM2.0-TSS
    - ./bootstrap && ./configure && make -j$(nproc)
    - sudo ../.ci/travis-tss-install.sh
    - popd
    - sudo ldconfig /usr/local/lib
    - git clone https://github.com/01org/tpm2-abrmd.git
    - pushd tpm2-abrmd
    - ./bootstrap && ./configure --with-dbuspolicydir=/etc/dbus-1/system.d && make -j$(nproc) && sudo make install && popd
    - sudo mkdir -p /var/lib/tpm
    - sudo groupadd tss && sudo useradd -M -d /var/lib/tpm -s /bin/false -g tss tss
    - sudo pkill -HUP dbus-daemon
    - sudo -u tss tpm2-abrmd --tcti=socket &
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/c/cmocka/libcmocka-dev_1.0.1-2_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/c/cmocka/libcmocka0_1.0.1-2_amd64.deb
    - sha256sum libcmocka-dev_1.0.1-2_amd64.deb | grep -q edb0dcfa14893b0a03375c4fe3b852043ce8fca8f2397cde340562554f6d50eb
    - sha256sum libcmocka0_1.0.1-2_amd64.deb | grep -q 797155b45a8288a860c4ed9dd3f161420f09ebf362de30166d9f6b98bfc27dd0
    - sudo dpkg -i libcmocka0_1.0.1-2_amd64.deb
    - sudo dpkg -i libcmocka-dev_1.0.1-2_amd64.deb

script:
    - ./.ci/travis-build-and-run-tests.sh
