language: cpp
compiler:
  - gcc

# This is a lie: we don't need sudo but this is required to get an
# Ubuntu image with a libc that isn't ancient, and with cmocka libs.
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - autoconf-archive
    - openssl
    - libssl-dev
    - libcurl4-openssl-dev
    - libdbus-1-dev
    - libglib2.0-dev
    - libcmocka0
    - libcmocka-dev

install: 
    - wget https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm532.tar
    - sha256sum ibmtpm532.tar | grep -q abc0b420257917ccb42a9750588565d5e84a2b4e99a6f9f46c3dad1f9912864f
    - mkdir ibmtpm532 && pushd ibmtpm532 && tar xzf ../ibmtpm532.tar && pushd ./src && make
    - ./tpm_server &
    - popd && popd
    - git clone https://github.com/01org/TPM2.0-TSS.git
    - pushd TPM2.0-TSS
    - ./bootstrap && ./configure && make -j$(nproc) && sudo make install && popd
    - sudo ldconfig /usr/local/lib
    - git clone https://github.com/01org/tpm2-abrmd.git
    - pushd tpm2-abrmd
    - ./bootstrap && ./configure --with-dbuspolicydir=/etc/dbus-1/system.d && make -j$(nproc) && sudo make install && popd
    - sudo mkdir -p /var/lib/tpm
    - sudo groupadd tss && sudo useradd -M -d /var/lib/tpm -s /bin/false -g tss tss
    - sudo pkill -HUP dbus-daemon
    - sudo -u tss tpm2-abrmd --tcti=socket &

before_script:
  - ./bootstrap

script:
  - mkdir ./build
  - pushd ./build
  - ../configure --enable-unit
  - make -j$(nproc)
  - make -j$(nproc) check
  - make -j$(nproc) clean
  - ../configure --enable-unit --without-tcti-tabrmd
  - make -j$(nproc)
  - make -j$(nproc) check
  - make -j$(nproc) clean
  - ../configure --enable-unit --without-tcti-socket
  - make -j$(nproc)
  - make -j$(nproc) check
  - make -j$(nproc) clean
  - ../configure --enable-unit --without-tcti-device
  - make -j$(nproc)
  - make -j$(nproc) check
  - popd
  - pushd ./test/system
  - PATH=$(pwd)/../../build/tools:${PATH} ./test_all.sh
  - popd
